apiVersion: v1
kind: Service
metadata:
    name: mybestservice
    labels:
        app: nginx
spec:
  image:  nginx:latest
  labels:
       app: nginx
  LoadBalancer: Yes 
  ClusterIP:   None
  
  ###############################3
  
  
  Changes from geeta devops class
  
  
  
  
       
